FROM node:18-alpine3.16 AS builder
# 앱 디렉터리 생성
WORKDIR /react-portfolio-website

ENV PATH="./node_modules/.bin:$PATH"
COPY package.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx
COPY --from=builder /react-portfolio-website/build /usr/share/nginx/html
