version: "3.8"

services: 
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/react-portfolio-website
    ports:
      - "8080:80"
    command: npm start

    